version: '2'
services:
    jsa-app:
        image: jsa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jsa-mysql:3306/jsa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jsa-mysql:
        extends:
            file: mysql.yml
            service: jsa-mysql
